### ISSUE TITLE
What's the difference between Godot RL agents and Godot AI Gym?

### ISSUE THREAD

**Issue by DrAlta** [edbeeching/godot_rl_agents#10]
[Godot AI Gym](https://github.com/lupoglaz/GodotAIGym) seems to be an older and more mature project.

Is there some significant design differences between the two? Or is it you just never heard of the other one before?

**Comment by edbeeching** [comment]
I was aware of both [Godot AI Gym](https://github.com/lupoglaz/GodotAIGym) before I started this project. The main disadvantage of Godot AI Gym are:

-  It requires compilation of the Godot Game Engine from source, which can deter new users. Godot RL Agents works out of the box with no need to recompile.
- It currently only works on Linux. Godot RL Agents has been tested on Linux and Windows, and should also work on Mac but I have not tested it.
- To implement a new environment the user is required to create it both in python and in the Godot Engine. Environments in Godot RL Agents can be made in just the Godot game engine. All the wrapping of observations and action sizes is handled automatically on the python side.
- The example environments in Godot AI Gym are limited, single agent examples. Godot RL agents contains example environments with parallization out of the box.

One advantage that Godot AI Gym may have over Godot RL Agents is that of speed, but I would need to benchmark this. Godot AI Gym passes observations through shared memory whereas Godot RL Agents uses TCP connections to send observations and receive actions.

I will close the issue but please feel free to open it if you have further questions.
