### ISSUE TITLE
Invalid get index '0' (on base: 'Array[Node]'). 

### ISSUE THREAD

**Issue by kasmith11** [edbeeching/godot_rl_agents#100]
I am following the tutorial [here](https://github.com/edbeeching/godot_rl_agents/blob/main/docs/CUSTOM_ENV.md) and am running into an error (image below). This is happening after using `gdrl` within a conda environment on windows (second image). Please let me know if there is any further information I can provide.

![image](https://user-images.githubusercontent.com/29484286/230797364-051a1dbb-e752-440e-a885-a18303497c41.png)

![image](https://user-images.githubusercontent.com/29484286/230797428-2ef8ef19-e359-4926-8a64-b6391badc5b1.png)

**Comment by edbeeching** [comment]
It is possible that you need to add the AIController3D to the a group called "AGENT". If you need more details on how to do this I can provide them. I will add this information to the tutorial as soon as I can.

**Comment by kasmith11** [comment]
Since I'm newer to Godot and godot-rl could you provide more detail? Also, would it be helpful for me to add this information to the tutorial via a pull request once we figure out the solution?

**Comment by edbeeching** [comment]
@kasmith11 , sure. Click on the AIController3D, then on the top right you can add it to the agent group like this:
![image](https://user-images.githubusercontent.com/7275864/230909061-d4eae2ce-e13f-4d6e-858f-a08691635442.png)

I think a newer version of the plugin should do this automatically, I just need to push an update.

Let me know if that works.

**Comment by kasmith11** [comment]
@edbeeching Adding the agent group fixed the error I was running into! Thank you.

My thinking now is that I can add your directions to this file [here](https://github.com/edbeeching/godot_rl_agents/blob/main/docs/CUSTOM_ENV.md) including what you mentioned above as a small note under this section:

![image](https://user-images.githubusercontent.com/29484286/231001323-2c0ba983-b786-45b9-b454-aa74523d0c49.png)
