### ISSUE TITLE
Benchmark the RL agents

### ISSUE THREAD

**Issue by GeorgeS2019** [edbeeching/godot_rl_agents#104]
We need an immediate glance the coverage of the supported RL libraries. 
ALL aspects implemented or e.g. 85% implemented. 

With that overview, one can decide which of the 3 supported libraries to use

For SB3 which export ONNX, only this option is more feasible to use c# for godot4

**Comment by visuallization** [comment]
@GeorgeS2019 Can you give a more detailed example of what you do have in mind here?

I am currently benchmarking the different rl backends in godotrl in terms of learning and runtime performance for my master thesis. But it sounds like you are more interested in having a comprehensive list of what is supported in the different rl libs, correct?

**Comment by GeorgeS2019** [comment]
@visuallization 
The future moving forwards for Godot is to replace python with language that is supported through GDExtension e.g. C#  With that, training and inference are all done using One langauge

https://github.com/edbeeching/godot_rl_agents/discussions/114#discussioncomment-6382743
