### ISSUE TITLE
Problems with AIController3D

### ISSUE THREAD

**Issue by Miner34dev** [edbeeching/godot_rl_agents#107]
Hello, i'm trying to create a simple RL 3D platformer, but it never works.
I fixed the errors in my code but then the script "sync.gd" started having a problem during initialization.
Can somebody help me?

**Comment by edbeeching** [comment]
Perhaps it is this issue, mentioned at the bottom of the custom env tutorial?

NOTE: If you receive an error Invalid get index '0' (on base: 'Array[Node]') click on AIController3D and add an AGENT group by clicking on Node, clicking on Groups, typing in AGENT and clicking Add to add the new group.

![image](https://github.com/edbeeching/godot_rl_agents/assets/7275864/5721ecd2-0eea-4bb2-a38c-6cfc1b92b860)

**Comment by Miner34dev** [comment]
Ok, now sync.gd works, but i still have problems, now on get_observation().
It says "Attempt to call function 'get_observation' in base 'null instance' on a null instance".
Here is my AIController3D extension code:
```GDscript
extends AIController3D

var fw_bw_move = 0.0
var r_l_move = 0.0
var jump = 0
var raycast

func _ready():
	raycast = $root/Node3D/Player/Raycast

func get_obs() -> Dictionary:
	var obs = raycast.get_observation()
	return {"obs":obs}

func get_reward() -> float:	
	return reward
	
func get_action_space() -> Dictionary:
	return {
		"fw_bw_move" : {
			"size": 1,
			"action_type": "continuous"
		},
		"r_l_move" : {
			"size": 1,
			"action_type": "continuous"
		},
		"jump" : {
			"size": 1,
			"action_type": "discrete"
		},
		}
	
func set_action(action):	
	fw_bw_move = clamp(action["fw_bw_move"][0], -1.0, 1.0)
	r_l_move = clamp(action["r_l_move"][0], -1.0, 1.0)
	jump = clamp(action["jump"][0], 0.0, 1.0)```

I renamed the raycast sensor to "Raycast".

**Comment by Miner34dev** [comment]
And there is a screenshot of my object hierarcy:
![Schermata del 2023-05-24 20-58-46](https://github.com/edbeeching/godot_rl_agents/assets/134534394/3d3037e1-ea9b-43b5-905d-6aad909981f6)

**Comment by edbeeching** [comment]
Hmm strange. Can you try making your raycast sensor a child of the AIController? 

I realize you probably don't want to do this as you want to move relative to the parent, I may have to revert to a change that was made. Originally AIController3D inherited from Node3D, but it was changed at some point and I think it was a mistake.

**Comment by Miner34dev** [comment]
I fixed it changing line 37 from
```GDscript
jump = clamp(action["jump"][0], 0.0, 1.0)
```
to
```GDscript
jump = clamp(action["jump"], 0, 1)
```

**Comment by Miner34dev** [comment]
But what does the terminal warning mean?

**Comment by edbeeching** [comment]
Most of the examples there are 16 copies of the env, to speed up training. In your case you just have one, so the batch size is probably too large for this configuration. Either make copies of the env or reduce the batch size.

**Comment by edbeeching** [comment]
I'm glad that you are making progress!

**Comment by Miner34dev** [comment]
Ok, just the thing i though, i need to configure the AIController.
Oh, and i have an idea on how to make the raycast sensor follow the player: I think if you set an AIController as scene root it will work!

**Comment by Miner34dev** [comment]
Ok, AIController as root works, and the raycast sensor follows the player.

**Comment by Miner34dev** [comment]
But where are those settings? I can never find them.

**Comment by edbeeching** [comment]
Which settings are you referring to?

**Comment by Miner34dev** [comment]
Batch size, n_envs...

**Comment by edbeeching** [comment]
n_envs is calculated automatically from the number of copies of the environment you have made in Godot. See the examples for an example of how to do this.

Batch size is configured in python. If you are using the sb3 backend you have refer to their docs to config it.  https://stable-baselines3.readthedocs.io/en/master/

**Comment by Miner34dev** [comment]
Ok, but to change n_steps and fps?

**Comment by edbeeching** [comment]
If you want more fine grained control, refer to this [example script] (https://github.com/edbeeching/godot_rl_agents/blob/main/examples/stable_baselines3_example.py)

For the fps, there is a speedup option to enable higher than real time training

**Comment by Miner34dev** [comment]
No, the examples ran at 60 fps while the my is at 7.5, and this should bee configured in godot because i used the same command for both of them (```gdrl```).

**Comment by edbeeching** [comment]
The reason you see 7.5 is because of action_repeat. The action is repeated 8 times, so you have an FPS of 60. You can also use `--speedup=8` if you want to train at faster than real time.

**Comment by Miner34dev** [comment]
Ok, but where is that setting? in sync.gd?

**Comment by edbeeching** [comment]
It is an export of the sync node, but you can also pass it as an argument to gdrl. For example:
```
gdrl --env=gdrl --env_path=examples/godot_rl_JumperHard/bin/JumperHard.x86_64 --viz --speedup=8
```

I highly recommend that you read the [Advanced tutorials](https://github.com/edbeeching/godot_rl_agents#advanced-usage) in the readme and I think that should answer most of your questions.

**Comment by edbeeching** [comment]
@Miner34dev , did you manage to resolve this? Can I close this issue?

**Comment by Miner34dev** [comment]
Why is my fps (the fps shown in the terminal) still at 7 after changing action_repeat?

**Comment by edbeeching** [comment]
Do you change it from the command line or in the editor?

**Comment by edbeeching** [comment]
@Miner34dev perhaps this is relevant to you: https://github.com/edbeeching/godot_rl_agents_plugin/pull/13

I will push the change to the plugin.

**Comment by Miner34dev** [comment]
How to update the plugin?

**Comment by edbeeching** [comment]
You can search for it on Godot assets.

However a simpler solution for you would be to change the following lines in sync.gd on your machine: https://github.com/edbeeching/godot_rl_agents_plugin/pull/13/files#diff-f787f8c54d9f84053c0eb814c447443bcd5f657ea525b827e375ceb51db71477

**Comment by Ivan-267** [comment]
Hello @Miner34dev, one other way to update the plugin to the latest version available is to download it from the repository, and then copy the `addons` folder to the Godot project folder (replace the old `addons` folder):

https://github.com/edbeeching/godot_rl_agents_plugin/tree/main

I will close this issue for now, but feel free to open a new issue if you run into any other issues.
