### ISSUE TITLE
Real time speed up feature

### ISSUE THREAD

**Issue by Miner34dev** [edbeeching/godot_rl_agents#109]
Hello, i'm here to report a bug/missing feature: the speed up doesn't work if changed while executing.
There's the code that changes the speed up value:
```GDscript
func _physics_process(_delta):
	if spdupbut.button_pressed:
		syncronizer.speed_up = 2
	else:
		syncronizer.speed_up = 1
```
Where spdupbut is a switch button and syncronizer is sync.gd.
Nothing changes when clicking the button, even the AI fps stays still.

**Comment by edbeeching** [comment]
I don't see the need for this feature. Typically you would build the environment and train in headless at higher speeds.

**Comment by Miner34dev** [comment]
In the near future i want to create a game with some AI's as enemies and more, and i want it with a timewarp feature.
I'm not saying that's an important feature which should be added as soon as possible, but that it can be useful especially in full games, which is the thing i'm planning to do.
Oh, and a slow down feature? I think it can be useful too.
You are experimenting with exportation with no dependencies for the next update, right? This is a little change but flanked with the enhanced export feature this can become a thing to be used for real games, not only simple AI tests.

**Comment by edbeeching** [comment]
Hi @Miner34dev , yes models can now be exported in ONNX format. So you should be able to bundle them with a game. As for the time warp feature, I think this is too specific for this use case.

**Comment by Ivan-267** [comment]
@Miner34dev would it be OK to close this issue?
