### ISSUE TITLE
BallChase example: Does best_fruit_distance need a reset after collection?

### ISSUE THREAD

**Issue by mischkadb** [edbeeching/godot_rl_agents#11]
I am not sure if I understand the examples correctly. In the BallChase example best_fruit_distance is initialized and reset in the reset() method. But shouldn't it also be reset after every fruit collection? Only the distance reduction to the first fruit gets rewarded at the moment.

**Comment by edbeeching** [comment]
Good spot, this is not working as intended. It dates back to when the task was to collected one fruit and then the environment would reset I then extended the task to multiple fruits. I am planning to push a number of fixes to master today. I will aim to include this as well.

**Comment by edbeeching** [comment]
I've corrected this bug in the latest release. Please let me know if you spot anything else or have other questions.
