### ISSUE TITLE
sb3 training error: AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>...

### ISSUE THREAD

**Issue by Ivan-267** [edbeeching/godot_rl_agents#119]
Test on my newest PR (which is a simple .md file change) failed: https://github.com/edbeeching/godot_rl_agents/pull/118/checks, a user also reported the same error on Discord with `JumperHard.x86_64,` and I was able to confirm the error on Windows with the `gdrl` command as well by uninstalling stable baselines and installing gdrl again using `pip install godot-rl`. 

The error is:
`AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>, <class 'gymnasium.spaces.discrete.Discrete'>, <class 'gymnasium.spaces.multi_discrete.MultiDiscrete'>, <class 'gymnasium.spaces.multi_binary.MultiBinary'>) as action spaces but Box(-1.0, 1.0, (2,), float32) was provided`

In my yesterday's PR the tests passed, so I checked to find differences, and so far I found some differences:
New (failing test): 
```
platform linux -- Python 3.7.17, pytest-7.4.0, pluggy-1.2.0
Downloading stable_baselines3-2.0.0-py3-none-any.whl (178 kB)
```
Previous (passed test):  
```
platform linux -- Python 3.7.17, pytest-7.3.2, pluggy-1.2.0
Downloading stable_baselines3-1.8.0-py3-none-any.whl (174 kB)
```

I also found this thread that might be related:
https://stackoverflow.com/questions/75108957/assertionerror-the-algorithm-only-supports-class-gym-spaces-box-box-as-acti

and the following here: https://github.com/DLR-RM/stable-baselines3/releases

> Breaking Changes:

    Switched to Gymnasium as primary backend, Gym 0.21 and 0.26 are still supported via the shimmy package

**Comment by Ivan-267** [comment]
Closing the issue as it should be fixed with the PR https://github.com/edbeeching/godot_rl_agents/pull/120

**Comment by anunknowperson** [comment]
I have this error too with clean installation on all examples

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\gdrl.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\godot_rl\main.py", line 91, in main
    training_function(args, extras)
  File "C:\Python310\lib\site-packages\godot_rl\wrappers\stable_baselines_wrapper.py", line 76, in stable_baselines_training
    model = PPO(
  File "C:\Python310\lib\site-packages\stable_baselines3\ppo\ppo.py", line 104, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 81, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\stable_baselines3\common\base_class.py", line 180, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>, <class 'gymnasium.spaces.discrete.Discrete'>, <class 'gymnasium.spaces.multi_discrete.MultiDiscrete'>, <class 'gymnasium.spaces.multi_binary.MultiBinary'>) as action spaces but Box(-1.0, 1.0, (2,), float32) was provided
