### ISSUE TITLE
pip install godot-rl[all] does not work

### ISSUE THREAD

**Issue by visuallization** [edbeeching/godot_rl_agents#127]
Hey there, 
currently `pip install godot-rl[all]` does not work because of conflicting dependencies.
godotrl requires gym 0.26.2 and ray[rllib] requires gym < 0.24.0.
One way to fix this would be to upgrade ray + ray[rllib] to 2.3.0, but we would need to rewrite the ray_wrapper a bit.

I started to look into this but wasn't able to make it work in the little time I currently have.
I created this issue so we keep track of this - whoever feels like tackling this, feel free to do so! :)

**Comment by edbeeching** [comment]
closing as we have a workaround for now
