### ISSUE TITLE
The framework is not easy to use.

### ISSUE THREAD

**Issue by ChernyakKonstantin** [edbeeching/godot_rl_agents#147]
I developed my own version of Godot-Python framework for RL when found this repo.
I tried to use this repo, but found it compicated in contrast to my version.
So I suggest to borrow some ideas from my implementation: https://github.com/ChernyakKonstantin/godot_rl.
My version can send any type of data as well through unified interface.

**Comment by edbeeching** [comment]
Thanks for your comments. Can you provide any more details about what you find difficult to use?

**Comment by edbeeching** [comment]
Hi @ChernyakKonstantin , I will close this issue unless you have any more details.

I had a look at your repo, I like the protobuf stuff, but I think it requires the user to code too much on the python side. For example, having the reward function defined in python is far less flexible than defining it in Godot. Also for each new env, the user has to create a new GodotEnvironment child class in python.

**Comment by ChernyakKonstantin** [comment]
Hi @edbeeching. 

I didn't like lack of capabilities to transfer large data (e.g. images), lack of modularity (it was not easy to understand how code works) and what examples are some sort of being broken (sorry, I can't remember exactly their names).

From you comment I see that we follow different paradigms how the frameworks work, so you can close the issue if you want.
