### ISSUE TITLE
[Potential todo, UX] - Implement sb3 example commands in `gdrl`

### ISSUE THREAD

**Issue by Ivan-267** [edbeeching/godot_rl_agents#149]
As we discussed previously on discord, one idea is to implement the functionality from the sb3 example to the gdrl command, I'm adding it here as a potential todo for discussion / tracking.

Since most of the arguments would be specific to sb3, the other frameworks would need to have different commands, e.g. `gdrl-rllib`, `gdrl-sf`, `gdrl-cleanrl` and each could contain corresponding arguments. 

`gdrl --help` would then return all arguments specific to sb3, and the others would return arguments specific to the framework.

The benefits would be that it simplifies the UX for new users, and the steps that need to be described in potential future starter tutorials would also be simpler.

**Comment by edbeeching** [comment]
I think we will deprecate `gdrl` and just use the examples to lower the maintenance overhead. Closing.
