### ISSUE TITLE
Can the training process also visible?

### ISSUE THREAD

**Issue by AleatorM** [edbeeching/godot_rl_agents#15]
Hello, Ed! Your work is awesome. Have a quick question though. While I can see how the game is going when performing eval using your pretained model, trying to train the model just provides me the cmd box printing the training information. Can the training process also visible with some settings?

**Comment by edbeeching** [comment]
Hi, thanks. In the yaml config file you can set **show_window: true** to show the window(s) and visualize the training process.
Depending on your use case this may slow down training. I will close the issue but feel free to reopen it or raise another one with any other questions.
