### ISSUE TITLE
Questions on performance and headless

### ISSUE THREAD

**Issue by MarcoMeter** [edbeeching/godot_rl_agents#17]
Hi @edbeeching 

thanks for your API!

I've got two questions:
In your paper you state that 12k interactions per second are recorded. How many environments ran in parallel for this results?
Do you need X for running environments featuring visual observations? Your roadmap says that headless is not supported yet.

I'm basically looking for alternatives to ml-agents that run significantly faster. Like one Unity build with only one environment is capable of only generating like 200-300 interactions per second.

**Comment by edbeeching** [comment]
Hi, 
For the 12k interactions it was running 4 parallel environments with 16 agents instatiated inside each env and action repeat of 4.
For both Godot and Unity, one of the best ways to speed things up is by having several instances of your problem defined in your Unity/Godot Scene. You will see in my examples I use 16, but I have done other tests where I scale up to 64 agents.

I am still not sure about X, I have meaning to run some more detailed tests. At the moment I am waiting for Godot 4 beta and then I plan to expand on the features available in the framework.

**Comment by edbeeching** [comment]
closing, let me know if you have more questions.
