### ISSUE TITLE
Unable to run godot-rl (stablebaselines3)

### ISSUE THREAD

**Issue by haseebzeeshan2010** [edbeeching/godot_rl_agents#186]
I followed the following steps from this tutorial that was listed on the godot_rl github page: https://www.youtube.com/watch?v=f8arMv_rtUU

My computer is running Ubuntu 22.04.4 LTS but I have tried with 24.04 LTS as well and there is no change in result

These are the steps I followed (as stated in the video):

Step 1-3

![Screenshot from 2024-05-23 14-35-27](https://github.com/edbeeching/godot_rl_agents/assets/30246451/20dc47a7-c0e5-4b9a-a17d-6389ea3948bc)

Step 4 - Download raw file

![Screenshot from 2024-05-23 14-47-49](https://github.com/edbeeching/godot_rl_agents/assets/30246451/532627c0-914d-4646-bcec-3b1289d76cb4)

Step 5 - Place it alongside the rl folder

![Screenshot from 2024-05-23 14-50-16](https://github.com/edbeeching/godot_rl_agents/assets/30246451/e742454f-f656-4d34-b687-fc2995813abb)

-----End of Python Setup----

Step 6 - Create project

![Screenshot from 2024-05-23 14-54-12](https://github.com/edbeeching/godot_rl_agents/assets/30246451/74e21e91-3a58-434e-ab47-06217a8de753)

Now the filesystem looks like this:

![Screenshot from 2024-05-23 14-55-48](https://github.com/edbeeching/godot_rl_agents/assets/30246451/627eb948-104b-4ad4-b7ac-123b6bf4924e)

Step 7 - Create CharacterBody3D

![Screenshot from 2024-05-23 14-57-45](https://github.com/edbeeching/godot_rl_agents/assets/30246451/1f2d3b45-d50a-402d-9372-15846dbcf950)

Step 8 - Add emission

![Screenshot from 2024-05-23 14-59-34](https://github.com/edbeeching/godot_rl_agents/assets/30246451/1b8df58a-1931-4b83-99d0-918d53e7395c)

Step 9 - Add floor

![Screenshot from 2024-05-23 15-01-36](https://github.com/edbeeching/godot_rl_agents/assets/30246451/c2e5b078-5f62-46b1-b4af-94ba47ba094c)

Step 10 - Add target(Emission included in this step)

![Screenshot from 2024-05-23 15-05-00](https://github.com/edbeeching/godot_rl_agents/assets/30246451/ee7bd805-c042-4ea8-87a3-6bb8007c8a00)

Step 11 - Add walls

![Screenshot from 2024-05-23 15-57-04](https://github.com/edbeeching/godot_rl_agents/assets/30246451/b9cb767d-6cbe-4914-80a7-4d23553844c3)

Step 12 - Add template script for player

![Screenshot from 2024-05-23 16-05-58](https://github.com/edbeeching/godot_rl_agents/assets/30246451/5504191c-efbc-4a02-a6ea-a025c89521fa)

Step 13 - Add Camera3D

![Screenshot from 2024-05-23 16-12-29](https://github.com/edbeeching/godot_rl_agents/assets/30246451/0434ff8e-9d39-496b-85e5-31c93e8e2216)

Step 14 - Re-arrange target and cube in the scene

![Screenshot from 2024-05-23 16-14-11](https://github.com/edbeeching/godot_rl_agents/assets/30246451/87cd7f18-4010-4165-9bab-be39dd49ab48)

Step 15 - Add signals for wall and target to move cube back to original position

![Screenshot from 2024-05-23 16-19-22](https://github.com/edbeeching/godot_rl_agents/assets/30246451/92381490-73b1-436c-9154-5ec97d1d8eb2)

Step 16 - Comment out control code

![Screenshot from 2024-05-23 16-20-00](https://github.com/edbeeching/godot_rl_agents/assets/30246451/8d807ad5-3ad6-493c-8785-c1a9b1a76d90)

Step 17 - Download the godot_rl_agents_plugin-main.zip from github

![Screenshot from 2024-05-23 16-22-30](https://github.com/edbeeching/godot_rl_agents/assets/30246451/1af3fc58-b169-47dc-bd7d-af98839ef298)

Step 18 - Select the script_templates and addons folder

![Screenshot from 2024-05-23 16-27-11](https://github.com/edbeeching/godot_rl_agents/assets/30246451/93208ef3-829e-4ed3-a3bb-26c559060ac9)

Step 19 - Copy them over

![Screenshot from 2024-05-23 16-31-22](https://github.com/edbeeching/godot_rl_agents/assets/30246451/f090b778-48e6-4907-a149-c061a2059e16)

Step 20 - Enable the Plugin

![Screenshot from 2024-05-23 16-33-01](https://github.com/edbeeching/godot_rl_agents/assets/30246451/7ba3b43f-5e79-44e0-85d3-dcc90674e3f6)

Step 21 - Add and extend script of AIController3D

![Screenshot from 2024-05-23 19-39-14](https://github.com/edbeeching/godot_rl_agents/assets/30246451/ac1f27b0-b0f3-4396-bbc2-adc85e2b0e7c)

Add the script_templates script and edit it for purpose of the project

![Screenshot from 2024-05-23 19-52-15](https://github.com/edbeeching/godot_rl_agents/assets/30246451/75a8fafa-aea1-41b6-9aaa-e335ed96b76e)

Alter the cube.gd script for AI to control velocity

![Screenshot from 2024-05-23 19-55-07](https://github.com/edbeeching/godot_rl_agents/assets/30246451/2f6dd12e-1ced-490b-aa9e-b2d44dcfda3e)
![Screenshot from 2024-05-23 19-55-23](https://github.com/edbeeching/godot_rl_agents/assets/30246451/93c45b80-91fd-4dbb-830c-b811c381fd27)

Step 22 - Finally run the script in the virtual environment through: python3 stable_baselines3_example.py

Step 23 - Add the Sync node in godot

After all this an error appears:

![Screenshot from 2024-05-23 20-04-10](https://github.com/edbeeching/godot_rl_agents/assets/30246451/70a0ee29-170d-466b-9134-54821001d732)

Please check if I've missed a step, I've tried this in both the version of godot used in the tutorial (v4.2.dev1) and the latest stable version, but there is the same issue

Adding ": Node3D" in step 15 does not make a difference to the result

It would be very much appreciated if you could help with this issue

Thanks in advance

**Comment by Ivan-267** [comment]
Hello, I think it's a version mismatch issue. Try installing the latest version of Godot RL Agents from this repository (main branch).

**Comment by haseebzeeshan2010** [comment]
Thanks for the reply!

This might be a silly question, but are you saying to download the entire main branch(including examples, docs, godot_rl, godot_rl_agents_plugin) or just a specific folder?

If it is a specific folder, it would be really helpful if you could send the link. Just want to be sure I'm choosing the right one.

**Comment by Ivan-267** [comment]
For the main project, try using `pip install https://github.com/edbeeching/godot_rl_agents/archive/refs/heads/main.zip`.

For plugin (the files to copy to the Godot project), use the plugin repository to get the latest version: https://github.com/edbeeching/godot_rl_agents_plugin

**Comment by haseebzeeshan2010** [comment]
I used the command in the environment and installed the updated plugin but unfortunately the problem still persists.

I looked a little deeper into the error and it looks like the handshake does complete but then it returns a null value that the handle_message() function cannot manage and the server disconnects.

My logic could be mistaken as there might be a problem with the stable_baselines3_example.py(even though I've downloaded it from the correct branch) but here are some images of the error:

![Screenshot from 2024-05-24 10-30-14](https://github.com/edbeeching/godot_rl_agents/assets/30246451/a3e05f16-6ef4-453d-b62b-ea58f8192a58)

![Screenshot from 2024-05-24 10-32-18](https://github.com/edbeeching/godot_rl_agents/assets/30246451/0e276fdf-e1a1-40dd-9f8f-72ae6d5edaab)

**Comment by Ivan-267** [comment]
Perhaps you can try an example from the examples repository: https://github.com/edbeeching/godot_rl_agents_examples

You could also try unistalling godot rl agents with `pip uninstall` before installing (if you didn't try already).

**Comment by haseebzeeshan2010** [comment]
Thanks for the advice, will try and complete one of the examples before coming back to this

**Comment by haseebzeeshan2010** [comment]
I got the example working. Thanks for the help!
