### ISSUE TITLE
Latest Godot Pypi Package Does not Work with Latest Addon Version

### ISSUE THREAD

**Issue by MichaelrMentele** [edbeeching/godot_rl_agents#188]
The latest published pypi version of godot_rl does not work with the latest version of the addon. You need to install from main (thanks @Ivan-267) `pip install https://github.com/edbeeching/godot_rl_agents/archive/refs/heads/main.zip`. See https://discord.com/channels/1073582623349297253/1073582787807948820/1252344749151621183 for context.

We should cut a new release (however y'all are doing that) and update the package on pypi so that folks don't bounce off the project.

**Comment by edbeeching** [comment]
Closing, let me know if you are still having issues.
