### ISSUE TITLE
Sharing and loading pretrained models with Hugging Face

### ISSUE THREAD

**Issue by osanseviero** [edbeeching/godot_rl_agents#2]
Hi there! Thanks for this great contribution, this is an awesome project. 

I see you currently share the checkpoints in a directory within the repo [here](https://github.com/edbeeching/godot_rl_agents/tree/main/envs/checkpoints). Would you be interested in sharing your models in the [Hugging Face Hub](http://hf.co/models) instead? The Hub offers free hosting of over 25K models, and it would make your work more accessible and visible to the rest of the ML community.  Loading the models directly from the Hub could allow users to easily load any pretrained model from other users in the community!

Some of the benefits of sharing your models through the Hub would be:
* multiple features from [TensorBoard visualizations](https://huggingface.co/pyannote/segmentation/tensorboard), PapersWithCode integration, and more
* versioning, commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable
* wider reach of your work to the ecosystem

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. We also have a [library](https://huggingface.co/docs/hub/how-to-downstream) that allows programmatic downloading and uploading of models of the Hub, so it could be used to push models during training and enabling things such as 

```
gdrl --env_path envs/builds/JumperHard/jumper_hard.x86_64 -e --restore edbeeching/jumper_hard [optionally] --version 465d092

```

Please let us know if you would be interested and if you have any questions, we would be happy to provide guidance

Happy to hear your thoughts,
**Omar and the Hugging Face team**

cc @thomwolf

**Comment by edbeeching** [comment]
This issue is finally resolved!
