### ISSUE TITLE
Plug-in Install through Godot 4.3 asset library

### ISSUE THREAD

**Issue by ra9hur** [edbeeching/godot_rl_agents#200]
This is on Godot 4.3 stable version.

As per instruction in the link:
https://github.com/edbeeching/godot_rl_agents/blob/main/docs/CUSTOM_ENV.md

I am trying to install the plug-in through asset library. Searching for "RL" and godot-rl-agent does not get listed in the search results.

Attaching the snapshot of the search results for your reference, if that helps.

Sure, I am missing something very trivial. Pl help.

![image](https://github.com/user-attachments/assets/524063be-580a-47aa-b2cf-d3b7a568f9bc)

**Comment by Ivan-267** [comment]
Hello,

Please try installing the mono/.net version from https://godotengine.org/download/windows/, I just tried searching `godot rl` and `rl` with 4.3.stable.mono and it shows up for me on Windows.

If it still doesn't show up, an alternative way to install is to get the plugin repository (https://github.com/edbeeching/godot_rl_agents_plugin) and copy the files manually (`addons` folder would go inside the godot project folder: `godot_project/addons/godot_rl_agents`). After this, enable the plugin in Project settings > Plugins in Godot editor.

**Comment by ra9hur** [comment]
Thanks for  the  quick response. 

I missed mentioning that I have been using Ubuntu 22.04. So, alternative way to install through the plugin repository (https://github.com/edbeeching/godot_rl_agents_plugin) should be applicable.

Will try and revert for any questions.

**Comment by Ivan-267** [comment]
Alternative install should work, but hopefully installing from asset library will also work when using the .net version of Godot. I think with Ubuntu everything should work as well, although I personally didn't yet try GDRL with Linux.

Without .net, the plugin can still work for training, but the onnx inference option wouldn't work as it uses C#.

**Comment by ra9hur** [comment]
Based on the last line, if we have to train and perform inference, is it that Godot C# version should be the one that we should be using ?
Since there is no point training on Godot gd script version and then eventually switch to .Net version for inference.

**Comment by Ivan-267** [comment]
Yes, it's recommended to use the .net version for full functionality (specifically onnx inference).

**Comment by ra9hur** [comment]
It would be good to mention this somewhere in the README so that developers can start using .NET version in the first place.  
If you agree, may be keep this issue open until there is a corresponding PR.

Thanks again !!

**Comment by edbeeching** [comment]
hey @ra9hur , on 4.3 stable mono on linux I can see the plugin. Let me know if you still cannot find it

![image](https://github.com/user-attachments/assets/5d5cf92e-8894-47d2-a015-55d17a1b4465)

**Comment by Ivan-267** [comment]
> It would be good to mention this somewhere in the README so that developers can start using .NET version in the first place. 

Thanks for the suggestion, I agree and here's the PR:
https://github.com/edbeeching/godot_rl_agents/pull/201

**Comment by ra9hur** [comment]
"AssetLib" link is found  at 2 places.
1. Initial screen where we choose / import a project to begin with
2. Choose a project and now, we are on the project screen.

The screenshot attached above is when I was trying from the initial screen. This was not listing "Godot-RL-Agents".

Looking at screen attached by @edbeeching , I realized that there is a link on  the project screen as well. So, search through the project screen, "Godot-RL-Agents" shows up. It is a bit strange.

Just downloaded "4.3 stable mono on linux" and the behavior is consistent, gets listed only on the project screen. 

![image](https://github.com/user-attachments/assets/a75f11b8-83a7-4ee2-bfef-a063769f2a7c)

**Comment by Ivan-267** [comment]
@ra9hur 

Thanks for investigating. On the initial screen, it seems project templates and demos are available in the asset store. That second assetlib link after you start a project offers tools/plugins that you can add to an existing project. Godot RL Agents is in the `tools` category which is available after you open a project.

**Comment by Ivan-267** [comment]
@ra9hur Is this issue ready to close now?

**Comment by ra9hur** [comment]
Yes, have closed this.
