### ISSUE TITLE
Not able to initiate training

### ISSUE THREAD

**Issue by ra9hur** [edbeeching/godot_rl_agents#202]
Environment:
- Kubuntu 22.04
- Godot 4.3 mono for linux

I am following instructions as in the below link.
https://github.com/edbeeching/godot_rl_agents/blob/main/docs/CUSTOM_ENV.md

Have setup all steps. I tried both the options.
- gdrl
- python clean_rl_example.py

Then run the project from Godot.

gdrl times out after a few seconds (approximately 30) with the below standard error.
![image](https://github.com/user-attachments/assets/f5fb8acb-f2a2-4f80-98ac-6159c9c5bd1c)

I checked the status of the port using netstat.
![image](https://github.com/user-attachments/assets/7afc0fa7-d17d-4f3a-9510-bb7194c6737d)

There are no errors in Godot and ball moves randomly in 8 dummy envs. 
![image](https://github.com/user-attachments/assets/248b8ec4-4313-4a46-bbab-36de92653356)

There are no related issues on github. So assume, it has been working all along, but I am missing something very obvious. Please help.

**Comment by Ivan-267** [comment]
Hello,

Is there a `sync` node added to the scene you're starting and set to "training" mode (default)?

If so, could you try running one of the pre-made examples such as the BallChase env, just to see if everything works in that case, as the env should be ready for training: https://github.com/edbeeching/godot_rl_agents_examples/tree/main/examples/BallChase (you can download the entire examples repository as zip then open one of the projects such as BallChase in Godot Editor).

**Comment by ra9hur** [comment]
@Ivan-267 ,

Yes, sync is added with control mode set to training (default).

I tried BallChase env as you suggested. Everything works fine. There are a few differences when we load the project.

1. A new build project icon
![image](https://github.com/user-attachments/assets/e6496588-5eea-4033-8d1d-1d98aeb135c9)

2. Server connection messages as highlighted were missing.
3. A new MSBuild tab. This was again missing.
![image](https://github.com/user-attachments/assets/38c8c3b5-c14e-4ac1-8932-1e4d1f2cabf9)

Attaching the compressed project folder.
[RingPong.zip](https://github.com/user-attachments/files/16927009/RingPong.zip)

Thanks for all the help !!

**Comment by Ivan-267** [comment]
Hello,

I've taken a look at the project, to solve the issue, remove the `_ready()` method in `res://controller.gd` script and it should work.

The `AIController3D` class that is extended from has the following `_ready()` method already defined:
```
func _ready():
	add_to_group("AGENT")
```
This adds the AIController to the agent group, which is used by the `sync` node to detect it for training/inference/etc. If the method is overriden by the inheriting class, it won't add the AIController to the group (unless the line above is added), and so the sync node will not find any agents to train.

**Comment by ra9hur** [comment]
Got it,  it works now. Thanks for your time !!

**Comment by Ivan-267** [comment]
You're welcome. Closing this issue.
