### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by visuallization** [edbeeching/godot_rl_agents#22]
Hi there,

I am currently looking into your project and it looks super interesting.

Unfortunately I have troubles installing the environment on windows.
The first errors occur when running the instruction `conda env create` from the installation guide. See Screenshot:
<img width="404" alt="Screenshot 2022-10-23 112009" src="https://user-images.githubusercontent.com/6199277/197384487-142fec69-45c6-4cfb-8ac8-9558bfc48554.png">

Could it be that you are using packages for linux only? `_openmp_mutex=4.5` seems to be one of them.
Is there a way to get this project running on windows? Would be cool, because I am consider using it for my master thesis.

Cheers!

**Comment by visuallization** [comment]
Okay I got it to work thanks to this issue: https://github.com/edbeeching/godot_rl_agents/issues/14

But I am wondering what are the implications of removing all these dependencies? Will the project be slower without them or might something else break?

**Comment by edbeeching** [comment]
I think there should be no issues. By the way I am upgrade this project to Godot 4 sometime in the next month. So be sure to check back. Let me know if you run into any other issues.
