### ISSUE TITLE
Unable to install RL agents.

### ISSUE THREAD

**Issue by Jetpackjules11** [edbeeching/godot_rl_agents#24]
It says package not found:

(base) PS C:\Users\Jetpackjules\Downloads\godot_rl_agents-0.2.2> conda env create
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libffi=3.3
  - libunistring=0.9.10
  - libopus=1.3.1
  - libtasn1=4.16.0
  - openh264=2.1.1
  - x264=1!157.20191217
  - libidn2=2.3.2
  - libvpx=1.7.0
  - _openmp_mutex=4.5
  - lame=3.100
  - ncurses=6.3
  - gmp=6.2.1
  - freetype=2.11.0
  - gnutls=3.6.15
  - readline=8.1.2
  - nettle=3.7.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ld_impl_linux-64=2.35.1

**Comment by edbeeching** [comment]
This is a windows issue that I will resolve in a version I will release in the coming weeks. Please refer to this github issue for a temporary fix: https://github.com/edbeeching/godot_rl_agents/issues/14#issuecomment-1105764165

**Comment by Jetpackjules11** [comment]
That worked perfectly! I managed to finish the installation process.

But, when I try to launch the example projects.. I get this (nothing ahppens when I try to run them and ignore/fix dependencies): 

![image](https://user-images.githubusercontent.com/113214256/206932837-41c7e20e-a55f-4f3e-ada8-b48a2c5e8457.png)

And this when I click "open anyway"
![image](https://user-images.githubusercontent.com/113214256/206932931-c393ba1e-df40-4130-8c6d-50302df711b7.png)

When I try to ignore all these errors and run the project anyway, a window opens then immediatly closes, and I get these messages:
![image](https://user-images.githubusercontent.com/113214256/206932981-3c13e1dc-cf18-412d-a495-2e32b6ef0e08.png)

(This is for the JumperHard project, but the same issue occurs with all the others examples)

Am I missing a dependancy/something else?

**Comment by Jetpackjules11** [comment]
Oops meant to keep it open sorry. (Look at message above)

**Comment by yaelatletl** [comment]
Check on the \godot_rl_agents\plugin\addons\ directory, you will find a folder named godot_rl_agents
you will find a file with the same name inside the res:://addons/ directory of the example you're trying to run, delete it and then place the folder 😄

**Comment by Jetpackjules11** [comment]
Thannks that fixed it!

Also encountered another issue (I seem to be a magnet for these)...

When I try to train or tun some of the examples, I recieve this message:
![image](https://user-images.githubusercontent.com/113214256/207243155-f91a177e-1aed-43e8-a253-9f5568991370.png)

When I try to run the godot project, I just see the balls not moving...
![image](https://user-images.githubusercontent.com/113214256/207243252-3031fa57-0263-49ef-90b8-a3074b4d5ba2.png)

Is my GPU unsupported? (I have an AMD Radeon 5600XT)

**Comment by Jetpackjules11** [comment]
Closed again by accident

**Comment by Jetpackjules11** [comment]
UPDATE: I was actually able to get everything working with some slight changes for windows!

But I still can't get my GPU to be seen (I have to set GPUs to zero in config for the training to run)

**Comment by edbeeching** [comment]
Unfortunately, most deep learning frameworks only support NVidia GPUs. For simple envs such as this one, you should be ok with using the CPUs but you may struggle with more complicated environments. I will close it for now but feel free to reopen it if you have any other issues / questions
