### ISSUE TITLE
How do I set the size of the Neural Network to [16, 16] in sb3?

### ISSUE THREAD

**Issue by ryash072007** [edbeeching/godot_rl_agents#32]
I noticed that the size is set to [64, 64] and changing it in the config file does nothing.
Btw, I managed to get my custom environment up and running and it works! Asking this question becoz it doesn't need a complex and large brain.

**Comment by edbeeching** [comment]
I have added a separate example file to this repo for sb3, examples/stable_baselines3_example.py .
You can find more info on how to configure the size of the nn in the sb3 docs [here](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html)
