### ISSUE TITLE
Improvements that may be needed in Custom ENV Doc

### ISSUE THREAD

**Issue by ryash072007** [edbeeching/godot_rl_agents#33]
It should be:
`"size": [len(get_obs()["obs"])],`
not:
`"size": len(get_obs()["obs"]),`
or an error arises

**Comment by ryash072007** [comment]
> It should be: `"size": [len(get_obs()["obs"])],` not: `"size": len(get_obs()["obs"]),`

else an error arises

**Comment by ryash072007** [comment]
The `zero_reward()` Has to be included in the Agent's script or sync.gd tries to execute a non-existent function which makes it so that the game does not run.

**Comment by ryash072007** [comment]
In the RaycastSensor script, you should make it optional to allow the raycasts to detect areas as it is not required always. Currently, it always sets the raycast to detect areas.

**Comment by ryash072007** [comment]
In the godot_rl_agents script, you should provide direct paths to the sync.gd and icon otherwise the plugin may not always activate. This means it can not be accessed in the add node window.

sync.gd direct path is "res://addons/sync.gd" .

**Comment by ryash072007** [comment]
The player/agent has to be in a group called "AGENT", please include this in the docs as well.

**Comment by ryash072007** [comment]
> The `zero_reward()` Has to be included in the Agent's script or sync.gd tries to execute a non-existent function which makes it so that the game does not run.

same for `var needs_reset`

**Comment by edbeeching** [comment]
That's for highlighting and fixing these issues. If you want to make a pull request that improves the docs it would be much appreciated. It is just me working on this project, mostly in my spare time.

**Comment by ryash072007** [comment]
#38 Created Pull Request.
