### ISSUE TITLE
What may be happening if Godot freezes when performing handshake?

### ISSUE THREAD

**Issue by ryash072007** [edbeeching/godot_rl_agents#36]
I'm using a Linux VM to run the sf part of the training and am using port-forwarding to allow it to communicate to my host computer. However, while performing handshake, the game just gets stuck. I have tried debugging this but nothing worked. Do you know what may be happening?

**Comment by edbeeching** [comment]
Is this with one of the example environments, or your own custom one?

**Comment by ryash072007** [comment]
This happens with the BallChase example environment.

**Comment by ryash072007** [comment]
Ill explain in detail:
I am running the sf part (Python part) in a Linux VM whereas Godot is running on Windows(The OS that my laptop uses).
The VM has a port forwarding rule such that it is a part of the localhost.
The handshake sequence does initiate but it waits forever in the `_get_dict_json_message` function.

**Comment by edbeeching** [comment]
Hmm it is hard to pin down the issue, I have not tested in this sort of configuration before.

**Comment by edbeeching** [comment]
Closing feel free to reopen if needed.
