### ISSUE TITLE
How can I make the training process last infinitely in sb3?

### ISSUE THREAD

**Issue by ryash072007** [edbeeching/godot_rl_agents#37]
The training process stops after a set amount of steps, so how would you make the training process run infinitely long, suppose overnight?

**Comment by edbeeching** [comment]
In the [sb3 example](https://github.com/edbeeching/godot_rl_agents/blob/main/examples/stable_baselines3_example.py) you can set the number of steps of model.learn(200000), set this to something like 10000000. I also recommend using speedup=8 as an argument when you create the env, as you can then train with accelerated physics so it should train faster. I recommend looking at the[ sb3 docs](https://stable-baselines.readthedocs.io/en/master/) if you want to know more.
