### ISSUE TITLE
Unable to open any example in the godot editor

### ISSUE THREAD

**Issue by Jetpackjules11** [edbeeching/godot_rl_agents#39]
I just get a message that says "the following file does not specify the version of godot with which it was created. If you proceed with opening it, it will be configured for godot's file format" and when I force open the project immediatly closes.  (this means I can't run "gdrl.interactive")

I also noticed that ryash072007 managed to get sb3 working to some extent, and would greatly appreciate any advice on how to accomplish that.

(I am using Anaconda Powershell prompt and Godot 3.5.1)

**Comment by Jetpackjules11** [comment]
Also, I encounter this error when trying to enable the Rl agents plufin (copied to the plugins folder)
![image](https://user-images.githubusercontent.com/113214256/210156948-008b65a2-1725-4824-84ee-faf75310fd67.png)

**Comment by edbeeching** [comment]
The latest version of the library supports Godot 4 only, would you like us to backport some features to Godot 3.5?

**Comment by ryash072007** [comment]
Actually, I found out that opening the Godot RL folder within the addons folder in the Godot Files viewer solves this issue. I dont know why that happens. For me, this is in Godot 4.

**Comment by ryash072007** [comment]
> I just get a message that says "the following file does not specify the version of godot with which it was created. If you proceed with opening it, it will be configured for godot's file format" and when I force open the project immediatly closes. (this means I can't run "gdrl.interactive")
> 
> I also noticed that ryash072007 managed to get sb3 working to some extent, and would greatly appreciate any advice on how to accomplish that.
> 
> (I am using Anaconda Powershell prompt and Godot 3.5.1)

Tips:
1. If using SB3, just do gdrl after activating your python environment.
2. Then wait until a text appears that "Press play in godot editor"
3. After that, play the example in the Godot Editor, it should work.

You are using Godot 3.5 which the plugin doesnt support, to my knowledge. Try Godot 4 Beta, Godot 4 Beta 10 came out.

**Comment by edbeeching** [comment]
@Jetpackjules11 I am closing this but feel free to reopen if you are still unable to use the library.

**Comment by Jetpackjules11** [comment]
Thanks for all the help! I was able to open the examples and get them working with Godot 4. I am still struggling to enable the plugin in a custom application, though. @ryash072007 you mentioned opening the godot RL folder in the files viewer? I tried this to no sucess :(...

**Comment by ryash072007** [comment]
You have to open the folder within the addons folder within godot. Then in the main plugin script, which has `add_custom_node`, you have to specify the full path for all the scripts mentioned.
Full Paths means `res://` path.

**Comment by ryash072007** [comment]
Btw, the plugin does not need to be enabled, just attach the sync.gd script found in the godot rl agents folder in addons folder in the project to a node2d or node3d. And it should work. Also look at the new docs for custom env.
