### ISSUE TITLE
AssertionError: incorrect file suffix for fileman when trying to run sb3 ball chase on windows 11

### ISSUE THREAD

**Issue by jruots** [edbeeching/godot_rl_agents#49]
**What happened:**
AssertionError when trying to run train.py file which is copy pasted from: https://github.com/edbeeching/godot_rl_agents/blob/main/examples/stable_baselines3_example.py
See error below.

**Steps:**
- Install Godot 3.5.1
- Create new virtual env godot_rlearning in python
- Install godot-rl into godot_rlearning with pip install godot-rl[sb3]
- Download example with gdrl.env_from_hub -r edbeeching/godot_rl_BallChase
- Create new train.py file with code copy pasted from link under "What happened"
- Open Anaconda Prompt and cd into project folder with train.py
- Run with python train.py
- Face AssertionError

**Troubleshooting:**
Tried googling and found zero results

**Other info:**
- OS: Windows 11
- Python: 3.10.9

Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\Python Workspace\godot-rl-test\train.py", line 8, in <module>
    env = StableBaselinesGodotEnv(env_path="C:/Users/xxxx/examples/godot_rl_BallChase/bin/BallChase.x86_64", show_window=True, speedup=8)
  File "C:\Users\xxxx\anaconda3\envs\godot_rlearning\lib\site-packages\godot_rl\wrappers\stable_baselines_wrapper.py", line 12, in __init__
    self.env = GodotEnv(env_path=env_path, **kwargs)
  File "C:\Users\xxxx\anaconda3\envs\godot_rlearning\lib\site-packages\godot_rl\core\godot_env.py", line 35, in __init__
    self.check_platform(env_path)
  File "C:\Users\xxxx\anaconda3\envs\godot_rlearning\lib\site-packages\godot_rl\core\godot_env.py", line 60, in check_platform
    pathlib.Path(filename).suffix == ".exe"
AssertionError: incorrect file suffix for fileman C:/Users/xxxx/examples/godot_rl_BallChase/bin/BallChase.x86_64 suffix .x86_64

**Comment by jruots** [comment]
Found the issue.
In https://github.com/edbeeching/godot_rl_agents/blob/main/examples/stable_baselines3_example.py
For windows you need to change the extension from .x86_64 to .exe as I'm guessing .x86_64 is some Linux thing

**Comment by edbeeching** [comment]
Thanks, yes you will need to change it to be a .exe extension. I will try to check and do this automatically in the future. Let me know if you have any other issues.
