### ISSUE TITLE
Clearer instructions needed

### ISSUE THREAD

**Issue by yaelatletl** [edbeeching/godot_rl_agents#5]
I feel like this project can be a great way to start working on ML, but clearer or otherwise extended instructions are needed, one may not figure out dependencies in other folders when checking the examples, or may not be able to execute the commands to run the trained examples

**Comment by edbeeching** [comment]
Thank you for your feedback. 

I assume you have followed the [examples](https://github.com/edbeeching/godot_rl_agents/blob/main/docs/EXAMPLE_ENVIRONMENTS.md) ?

I am would gladly extend the examples and documentation. Do you have some specific examples of dependencies or commands that you found unclear/broken? Are the difficulties on the python side of the interface or on the Godot side?

**Comment by yaelatletl** [comment]
I followed the examples, but I wasn't able to exectue commands starting with `gdrl `  wheter I should use python, directly run these from the conda powershell, I couldn't know.
Other thing that would help is to tell users to make sure they are launching CMD or powershell through Conda in the installation. 
Also I found that the examples, as you open them in godot have broken dependancies, though those are present in another folder in the project, specifically the addon files.

**Comment by jruots** [comment]
First off: love this project, great work! My 2 cents on clearer instructions would be to make 1-2 youtube videos where installation and setup is shown and another video where e.g. ball chase is created from scratch. I feel like this would get a bunch of new users kickstarted with godot rl faster.

**Comment by edbeeching** [comment]
There is now a video tutorial here: https://www.youtube.com/watch?v=f8arMv_rtUU
