### ISSUE TITLE
RaycastSensor3D not working in godot 3.5 version

### ISSUE THREAD

**Issue by visuallization** [edbeeching/godot_rl_agents#54]
Hey there,

Since `_spawn_nodes()` is commented in the `_ready` function in `RaycastSensor3D .gd` no rays are getting created which can hit the environment. Is there a reason why this commeted out? It makes RaycastSensor3D on the branch `godot3.5` somewhat useless.

Kind Regards

![grafik](https://user-images.githubusercontent.com/6199277/213947708-918bf2d5-2539-4b79-8c2c-b04ec26538d7.png)

**Comment by edbeeching** [comment]
Hi, the current version of the library supports 4.0 beta only.

In the [current version](https://github.com/edbeeching/godot_rl_agents_plugin) of the plugin, this line is not commented out. Where did you copy the plugin from?

**Comment by visuallization** [comment]
Hey there,

Thanks for the answer!
I got the plugin a few months ago (I think it was in October or November) from the `main branch` from this repo. It was at a time where the code still worked with godot 3.5. When copying the plugin from the `branch godot3.5` the raycast sensor is still not working because of the commmented line. It seems to work fine however if I just uncomment the line. I just wanted to make sure I am not missing something and wanted to know why the line was commented out in the first place (maybe something is still broken and I am not aware of it)

Cheers

**Comment by visuallization** [comment]
Edit* I just remembered: I got the version from the release page. More specifically I got the version 0.2.2 from here https://github.com/edbeeching/godot_rl_agents/releases/tag/v0.2.2

Cheers Mate

**Comment by yaelatletl** [comment]
Let me look into it :D

**Comment by yaelatletl** [comment]
This should be fixed now in the godot 3.5 branch, ported 4.0 features of the addon to it

**Comment by visuallization** [comment]
@yaelatletl Thanks for looking into this. I checked out the changes and used it in godot3.5. However I experienced some problems so I fixed it and created a PR. Feel free to merge it if you guys are agree with it. 

https://github.com/edbeeching/godot_rl_agents/pull/56
