### ISSUE TITLE
Improvements for version 0.6.0

### ISSUE THREAD

**Issue by edbeeching** [edbeeching/godot_rl_agents#59]
Suggested by @visuallization 

- [x] Provide a detailed and clean documentation on how to use things. I think that's one of the big features which decides if people will use a tool or not. Make it as easy as possible for new people to get started. Especially since RL is already hard enough. Currently the framework is still a lot of trial and error and some things only work on certain platforms without being documented.
- [ ] Provide a step by step video (+ text) tutorial on how to setup and train an agent with godot rl agents from scratch. I think this will help newcomers immensely to get started.
- [x] Make sure the provided releases actually work. It took me quite some time until I realized that the senord3d is not working in Releaes 0.2.2. I guess it makes sense to create a new release and remove the broken ones.
- [x] It would be cool, if we GDScript would provide interfaces so it gets really clear which methods and members the agent has to implement. I know GDScript does not support this, but maybe there is an alternative?

**Comment by GeorgeS2019** [comment]
@edbeeching 
Consider open Github Discussion for issues related to WIP e.g. documentation and tracking tasks needed to keep making progress

**Comment by GeorgeS2019** [comment]
@edbeeching 
Where are the Links to these completed tasks?
