### ISSUE TITLE
How would I view an Rlib model once I have trained it?

### ISSUE THREAD

**Issue by Jetpackjules** [edbeeching/godot_rl_agents#60]

**Comment by ryash072007** [comment]
> How would I view an sb3 model once I have trained it?
You can check https://github.com/ryash072007/godot_rl_agents_forked/blob/main/godot_rl/backend/sb3.py.

**Comment by Jetpackjules** [comment]
Thanks!

But what Rlib? is it similar?

**Comment by ryash072007** [comment]
I do not know about Rllib as I am unable to use it on my pc, sorry.

**Comment by edbeeching** [comment]
For rllib you should be able to launch with the same command line args used for training and add `--eval`

**Comment by Jetpackjules** [comment]
> For rllib you should be able to launch with the same command line args used for training and add `--eval`

This still works with just `gdrl`?

**Comment by edbeeching** [comment]
Hey @Jetpackjules , did you resolve this?

**Comment by Jetpackjules** [comment]
Not exactly, I just switched to Sb3.

Also, I did not have time to reply before the thread was closed, but I read the hugging face documentation, which helped a LOT with my project! Thank you for this awesome plugin!

**Comment by edbeeching** [comment]
Ok well, that is good I guess. I will close this issue then.
