### ISSUE TITLE
Godot 3.5 vs Godot 4

### ISSUE THREAD

**Issue by OscarPindaro** [edbeeching/godot_rl_agents#65]
Hi guys,
i'm really passionate about Reinforcement Learning and i started making a little project. Initially i started to develop on godot 4, since it's the version of godot that is "officialy" supported by your library. However godot 4 is still in beta, and i'm loosing too much time on figuring how godot 4 works rather than just code my project. 

I've just noticed that there is a branch for godot3.5, which i'm a bit more experienced. Are all  the features that are in the main branch present in the 3.5 branch? Which are the differences? how stable is it? Would you reccomend switching to the 3.5 version?

Thank you so much for your time.

**Comment by edbeeching** [comment]
Most of the features are included in the 3.5 branch. However, two new RL libs (CleanRL and sample factory) are not supported. There is an effort to backport these changes. Going forward, I only plan to support Godot 4. There is a release candidate due in the next few weeks, so it might be worthwhile upgrading to Godot 4. There are not many changes really.

I consider both the main branch and the 3.5 branch to be experimental beta software, so don't expect everything tho work flawlessly. Improvements and contributions are always welcome!

**Comment by OscarPindaro** [comment]
Yeah I understand that GodotRL can be considered a beta, and it's not a problem, I just want my game engine to be stable ahah Of couse given the chance i will contribute to this project, it looks very promising. 

Maybe when Godot 4 will be more mature i will try it, but right now i want to use all my 3.5 code base with no limitations.

**Comment by edbeeching** [comment]
Ok, in that case check out the 3.5 branch. Let me know if you find any bugs or missing features.
