### ISSUE TITLE
Jumper Hard example not working with stable baselines in godot 3.5

### ISSUE THREAD

**Issue by visuallization** [edbeeching/godot_rl_agents#71]
Hey there,

When I try to run the jumper hard example with stable baselines in godot 3.5. 
`gdrl --env_path .\envs\builds\JumperHard\jumper_hard.exe --config_file .\envs\configs\ppo_config_jumper_hard.yaml`
I do get the following error:

![grafik](https://user-images.githubusercontent.com/6199277/219618948-ae5b4273-9054-4927-9896-62d90b4bf5cd.png)

@yaelatletl Can you confirm that this does not currently work?

Cheers

**Comment by visuallization** [comment]
Okay I even got a similar issue with godot 4 version when downloading the BallChase example and running: `python examples/stable_baselines3_example.py --env_path=examples/godot_rl_BallChase/bin/BallChase.exe --speedup=8` 

I get 
![grafik](https://user-images.githubusercontent.com/6199277/219649770-30d49e97-cceb-44eb-90a9-06f0e3b08772.png)

**Comment by edbeeching** [comment]
Thanks for spotting this bug. I just fixed it on the godot 4 master branch. commit 6964f73ee4b3a73d1a17c393b12ce57e1587eab7 
I have not got around to updating the 3.5 branch. Feel free to submit a PR on this. Otherwise I will get round to it later this weekend. 

Let me know if you have any other issues.

**Comment by visuallization** [comment]
Nice, thanks for fixing! I can confirm this works now on all my tested environments.

**Comment by visuallization** [comment]
I just realized & please confirm if I get this right: maybe we shouldn't split between godot 3.5 and godot 4 in this repo, as the python algorithms seem to run for both versions and the only thing which breaks depending on the version is the godot plugin. So maybe it makes sense to differentiate between the 2 godot versions inside the godot plugin's repository and then make sure to have a stable main branch for this repo and continue further development on a dedicated `development` branch so people can get directly started from the main branch without worrying about things not working on main.
