### ISSUE TITLE
Version Compatibility 

### ISSUE THREAD

**Issue by yaelatletl** [edbeeching/godot_rl_agents#72]
I'm making this issue for discussion, as the suggestion by @visuallization in #71 is worth noting, the python module works either on Godot 3.5 or 4.0, and the addon code is now a submodule, so we could go back to having a single branch here and let users select for which version download examples and the addon.
This also applies to the C# ONNX loader, most of it could be written as version independent

**Comment by edbeeching** [comment]
This sounds good, it's easier to maintain as well.

**Comment by edbeeching** [comment]
Closing
