### ISSUE TITLE
A tutorial on creating custom envirionments

### ISSUE THREAD

**Issue by edbeeching** [edbeeching/godot_rl_agents#73]
Hi @visuallization , @yaelatletl and @ryash072007 .
As part of Hugging Face's Deep RL class, I have finally written a tutorial on how to create a custom environment.
You will find the draft of it [here](https://moon-ci-docs.huggingface.co/deep-rl-course/pr_177/en/unitbonus3/godotrl?fw=pt).

It would be great to hear your feedback on this before I add it to the docs.

It includes a new node/script I added to the addon, an AIController3D / 2D node. Which should make it simpler to add an AI agent and removes some boilerplate.

**Comment by visuallization** [comment]
@edbeeching Just scrolled through it and it looks nice! I especially like there is an AIController you can now extend from :)

Once I find more time, I will try to go through this and code along step by step to see if anything is missing or should be added.

**Comment by edbeeching** [comment]
Thanks for your feedback!
