### ISSUE TITLE
Add grid sensors

### ISSUE THREAD

**Issue by edbeeching** [edbeeching/godot_rl_agents#77]
Create:
- GridSensor2D & example 
- GridSensor3D & example 

Example of this sensor in UnityML Agents: https://blog.unity.com/technology/how-eidos-montreal-created-grid-sensors-to-improve-observations-for-training-agents

**Comment by Ivan-267** [comment]
I think we can close this as we have the [PR ](https://github.com/edbeeching/godot_rl_agents_plugin/pull/22) ready and the 3D example is done as well.

The only thing left to consider is a future 2D example.

**Comment by edbeeching** [comment]
@Ivan-267 good point, closing.
