### ISSUE TITLE
Problem With Installation

### ISSUE THREAD

**Issue by LunaticWyrm467** [edbeeching/godot_rl_agents#81]
### Main Issue

Hi there! I have unfortunately been unable to set up the environment that this requires due to the following issue:

![image](https://user-images.githubusercontent.com/65457004/223598842-9535f707-d60c-4e2e-ba33-e8b306ba5e84.png)

I am on the latest stable release, as the directory shows above.

### Side Suggestion

Also, I think the instructions for the installation should be clearer, as I really don't know how to set up my Godot project to work with this environment. Is there any documentation for this API? Is this like an addon, or a modification to Godot itself? This tool seems really powerful, and I would really like to use it, but there really isn't much to go off of in terms of tutorials or documentation in general.

My suggestion would be to have a short installation tutorial video somewhere to show how its done, as well as a brief introduction on how to work with the RL agents.

If there are any resources that I'm not familiar with, *please* let me know!

**Comment by edbeeching** [comment]
Hey. I just published release 0.4.7 which is up to date and works with Godot 4.0.
I suggest installing with `pip install godot-rl` or `pip install godot-rl[sb3]` if you want to use Stable Baselines 3 for training.

Be sure to check out the [examples](https://github.com/edbeeching/godot_rl_agents_examples).

I recently added a tutorial on how to create a custom environment [here](https://github.com/edbeeching/godot_rl_agents/blob/main/docs/CUSTOM_ENV.md).

We are aware that the docs need improvement. The next version, 0.5.0, aims to improve the docs and be a what I would consider the beta release of this software.

Feel free to reopen this issue if you have further problems with the installation.

**Comment by LunaticWyrm467** [comment]
Oh, thank you so much! I'll let you know if there are any other issues.
