### ISSUE TITLE
Banner for the repository

### ISSUE THREAD

**Issue by AleryBerry** [edbeeching/godot_rl_agents#86]
I think having a banner image would improve the appeal of the plugin and make more Godot developers aware of this project.

**Comment by edbeeching** [comment]
Thanks for raising this issue. I am not an artist, what do you imagine the banner looking like? Perhaps I can use stable diffusion to generate one.

**Comment by GeorgeS2019** [comment]
> make more Godot developers aware of this project.

## This is TOP priority

**Comment by GeorgeS2019** [comment]
Use **Godot_RL** label instead of Godot, or perhaps in addition to Godot label

**Comment by edbeeching** [comment]
Hi @GeorgeS2019 , thank you for your enthusiasm for this project. Please could you refrain from making some many comments, as every comment sends a message to my inbox, I received 10 emails this morning related to comments you made. 

If you would like to contribute to this repository then feel free to open a PR with the changes you would like to make.
