### ISSUE TITLE
Training an agent with WSL and sample-factory is not learning

### ISSUE THREAD

**Issue by visuallization** [edbeeching/godot_rl_agents#89]
Training an agent with WSL and sample-factory is not learning.

When running on Linux: `drl --trainer=sf --env=gdrl --env_path=examples/godot_rl_JumperHard/bin/JumperHard.x86_64 --num_workers=10 --experiment=JumperHard01 --viz --batched_sampling=True --speedup=8`

The training looks something like this:

![image](https://user-images.githubusercontent.com/6199277/227230443-42fce6cd-7285-4e61-b27f-588fa67a793e.png)

When running on WSL with the same command the training looks like this:

<img width="260" alt="image-2" src="https://user-images.githubusercontent.com/6199277/227230561-8cd342e9-4fb6-452d-8225-5d214ca54c8d.png">

As you can see on Linux the agent actually learns, whereas on WSL the agent does not learn.

This might be related to this issue:
https://github.com/alex-petrenko/sample-factory/issues/128

As stated in the issue you might be able to work around this by running the training on the CPU but it won't allow for large scale training.

**Comment by edbeeching** [comment]
Closing for now, but keeping pinned.
