### ISSUE TITLE
Outdated install instructions

### ISSUE THREAD

**Issue by metinc** [edbeeching/godot_rl_agents#92]
https://github.com/edbeeching/godot_rl_agents/blob/d6accb04a3ad1363a37e2d96a961e03c3eb49244/docs/INSTALLATION.md?plain=1#L9

Version 2.2.2 is almost 1 year old. Are there any instructions on how to use the latest version? `conda env create` no longer works since `environment.yml` was removed.

**Comment by edbeeching** [comment]
Good question, the installation intructions are in the README now. The INSTALLATION.md is deprecated. I will remove it.
Let me know if you have any trouble with the install.

**Comment by edbeeching** [comment]
Good question, the installation intructions are in the README now. The INSTALLATION.md is deprecated. I will remove it.
Let me know if you have any trouble with the install.
