### ISSUE TITLE
MacOS install instructions

### ISSUE THREAD

**Issue by AustereTriceratops** [edbeeching/godot_rl_agents#95]
There's an issue when I try to run this command on macOS:

`gdrl --env=gdrl --env_path=examples/godot_rl_<ENV_NAME>/bin/<ENV_NAME>.x86_64 --viz`

godot_env.py detects that I'm on a mac platform and seems to want an .app file, but there isn't one in the bin folder when I install the example environments with this command `gdrl.env_from_hub -r edbeeching/godot_rl_<ENV_NAME>`

Is there a way around this?

**Comment by AustereTriceratops** [comment]
Update: I built the project from the source code in [edbeeching](https://github.com/edbeeching)/[godot_rl_agents_examples](https://github.com/edbeeching/godot_rl_agents_examples). There were some minor project settings in Godot that needed to be changed. If you want, I can set up a branch/fork for them - I don't know if making those changes will break anything on Linux/Windows.

**Comment by edbeeching** [comment]
Ye ssorry, I am missing the build templates for Mac builds. There is a PR that adds Mac support for examples [here](https://github.com/edbeeching/godot_rl_agents_examples/pull/2). Perhaps try that one out?

**Comment by AustereTriceratops** [comment]
Thanks! I'll take a look. I managed to get one of the examples, JumperHard, up and running on my own. 

I encountered another bug that I believe is macOS-specific but easy to fix (just one line needs to be changed). Should I just make a PR for it?

**Comment by edbeeching** [comment]
Was it the position of `@tool` in the script? Either way feel free to make a PR, thanks.
